### ISSUE TITLE
Install Client does nothing

### ISSUE THREAD

**Issue by SaschMie** [brianmiller/phvalheim-client#3] opened 2022-12-15 18:55 UTC
The client is installed by an friend, and it launches valheim through the phval url but no addons and BepInEx overlay is not shown

Console shows correct path to valheim at startup

**Comment by brianmiller** [comment] 2022-12-15 19:15
Can you provide a screenshot of the client window that appears during launch?

**Comment by SaschMie** [comment] 2022-12-16 09:02
Actual we solved the problem, he installed valheim on drive D and Stream still got some of the files in drive C. The launcher detected the game as installed on drive C, so he deleted on D and reinstalled on C. Now its working :)

**Comment by brianmiller** [comment] 2022-12-26 19:12
Duplicate of https://github.com/brianmiller/phvalheim-client/issues/1

**Closed as completed by brianmiller** 2022-12-26 19:12 UTC
Labels: duplicate
